--- 
version: '3'

networks:
  confluent_default: 
    external: true
  mongo_default:
    external: true

services:
  generator: # service for generating fake IoT device data
    image: generator:0.1.0
    container_name: generator
    build:
      context: ./generator
      dockerfile: Dockerfile
    restart: always
    networks:
      - confluent_default
      - mongo_default
    ports:
      - "7000:7000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - ./generator/.env

  paai:
    image: paai:0.1.2
    container_name: paai
    build:
      context: ./paai
      dockerfile: Dockerfile
    restart: always
    networks:
      - confluent_default
      - mongo_default
    ports:
      - "8000:8000"
    env_file:
      - ./paai/.env
    deploy:
      replicas: 3 # Making it more scalable 
      restart_policy:
        condition: on-failure

