apiVersion: apps/v1
kind: Deployment
metadata:
  name: generator-deployment
spec:
  selector:
    matchLabels:
      app: generator
  replicas: 1
  template:
    metadata:
      labels:
        app: generator
    spec:
      containers:
      - name: generator
        image: generator
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 7000
        env:
          - name: PAAI_ENDPOINT
            value: http://paai-service.default.svc.cluster.local:8000