--- 
version: '3'
services:

  mongo:
    image: mongo:6.0.5
    container_name: mongo
    restart: always
    networks:
      - default
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminPasswd!23
      MONGO_INITDB_DATABASE: paai
    volumes:
      - data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro # For creating a user for paai database
    deploy:
      replicas: 1

  mongo-express: # Service for viewing MongoDB in the browser
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: adminPasswd!23
      ME_CONFIG_MONGODB_URL: mongodb://admin:adminPasswd!23@mongo:27017/

volumes:
  data:
networks:
  default: